# Generated by Django 2.0.1 on 2018-02-11 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrsvp', '0003_auto_20180211_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='finalize',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='myrsvp.Question'),
        ),
    ]
