# Generated by Django 2.0.1 on 2018-02-12 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myrsvp', '0004_auto_20180211_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusOne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plus', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_choice', models.CharField(choices=[('A', 'attend'), ('N', 'sorry, cannot attend'), ('D', 'have not decided yet')], default='A', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='plus_one',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='rsvp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='myrsvp.Event'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rsvp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plusone',
            name='plus_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_plusone', to='myrsvp.Event'),
        ),
        migrations.AddField(
            model_name='plusone',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_plusone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together={('rsvp', 'user')},
        ),
    ]
